services:
  server:
    image: hyentaejang/advancedproject
    build:
      tags:
        - advancedproject
      args:
        - NODE_VERSION=20.18.0
      dockerfile: Dockerfile
      pull: true
      context: .
    container_name: codeit_advancedproject_container
    environment:
      - SERVER_PORT=3000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_DB_PORT}/${POSTGRES_DB}?schema=public
      - NODE_ENV=production
    networks:
      - network-advancedproject

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    networks:
      - network-advancedproject
    volumes:
      - postgres-advancedproject-data:/var/lib/postgresql/data

networks:
  network-advancedproject:

volumes:
  postgres-advancedproject-data:
